export const PERMISSIONS = {
  CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  VIEW_EMPLOYEE: "VIEW_EMPLOYEE",
  MANAGE_ATTENDANCE: "MANAGE_ATTENDANCE",
  MANAGE_PAYROLL: "MANAGE_PAYROLL",
  MANAGE_LOANS: "MANAGE_LOANS",
  MANAGE_SHIFTS: "MANAGE_SHIFTS",
  MANAGE_DOCUMENTS: "MANAGE_DOCUMENTS",
  VIEW_REPORTS: "VIEW_REPORTS",
  MANAGE_COMPANY_POLICY: "MANAGE_COMPANY_POLICY",
  MANAGE_LEAVES: "MANAGE_LEAVES",
  APPROVE_LEAVES: "APPROVE_LEAVES",
  MANAGE_REQUESTS: "MANAGE_REQUESTS",
  APPROVE_REQUESTS: "APPROVE_REQUESTS",
  MANAGE_ROLES: "MANAGE_ROLES",
  VIEW_ROLES: "VIEW_ROLES",
  MANAGE_DEPARTMENTS: "MANAGE_DEPARTMENTS",
} as const

export type PermissionAction =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

export const COMPANY_OWNER_ROLE = "Company Owner"
